model:
    arch: frrnB
data:
    dataset: coco
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    ann_path: /home/a/Desktop/CMU/1-2/ic-net_coco/annotations
    im_path: /home/a/Desktop/CMU/1-2/coco/images
training:
    train_iters: 85000
    batch_size: 2
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 1.0e-4
    l_rate: 1.0e-4
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
